name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build And Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run lint
          npm run test:ci
          npm run build-storybook
        env:
          COGNITO_TOKEN_ENDPOINT: ${{ secrets.COGNITO_TOKEN_ENDPOINT }}
          NEXT_PUBLIC_LGTMEOW_API_URL: ${{ secrets.NEXT_PUBLIC_LGTMEOW_API_URL }}
          NEXT_PUBLIC_IMAGE_RECOGNITION_API_URL: ${{ secrets.NEXT_PUBLIC_IMAGE_RECOGNITION_API_URL }}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
